services:
  - type: web
    name: pestai-main-app
    env: node
    plan: free
    buildCommand: cd client && npm install --include=dev && npm run build && cd ../server && npm install && npm rebuild sqlite3 --build-from-source
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ML_SERVICE_URL
        fromService:
          type: web
          name: pestai-ml-service
          envVarKey: RENDER_EXTERNAL_URL

  - type: web
    name: pestai-ml-service
    env: python
    plan: free
    buildCommand: cd ml_service && pip install -r requirements.txt
    startCommand: cd ml_service && uvicorn main:app --host 0.0.0.0 --port $PORT
